name: Upload Breakfast Menu

on:
  repository_dispatch:
    types: [upload-breakfast]

jobs:
  upload-breakfast:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Install dependencies
        run: ./gradlew build --no-daemon

      - name: Download breakfast menu from Slack and save to Firestore
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          FILE_ID: ${{ github.event.client_payload.file_id }}
        run: ./gradlew run --args="$FILE_ID"
